apiVersion: v1
data:
  PORT: {{ toString .Values.configmap.port}}
  RDS_PORT: {{ toString .Values.configmap.rds_port}}
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: {{.Values.configmap.name}}
